/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_AHB1ENR (*((volatile uint32_t*)0x40023830))
#define RCC_APB1ENR (*((volatile uint32_t*)0x40023840))

#define GPIOA_MODER (*((volatile uint32_t*)0x40020000))
#define GPIOA_ODR   (*((volatile uint32_t*)0x40020014))

#define TIM2_CR1    (*((volatile uint32_t*)0x40000000))
#define TIM2_CNT    (*((volatile uint32_t*)0x40000024))
#define TIM2_PSC    (*((volatile uint32_t*)0x40000028))
#define TIM2_ARR    (*((volatile uint32_t*)0x4000002C))

void delay_ms(uint32_t ms);

int main(void)
{
    RCC_AHB1ENR |= (1 << 0);   // GPIOA clock
    RCC_APB1ENR |= (1 << 0);   // TIM2 clock

    GPIOA_MODER &= ~(3 << 10);
    GPIOA_MODER |=  (1 << 10); // PA5 output

    TIM2_PSC = 16000 - 1;      // 1 ms tick (assuming 16 MHz clock)
    TIM2_ARR = 500;
    TIM2_CR1 |= (1 << 0);      // Start timer

    while(1)
    {
        GPIOA_ODR |= (1 << 5);   // LED ON
        delay_ms(500);

        GPIOA_ODR &= ~(1 << 5);  // LED OFF
        delay_ms(500);
    }
}

void delay_ms(uint32_t ms)
{
    TIM2_CNT = 0;

    while(TIM2_CNT < ms);
}

