/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

/* ================= RCC ================= */

#define RCC_AHB1ENR    (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR    (*(volatile uint32_t*)0x40023840)

/* ================= GPIOA ================= */

#define GPIOA_MODER    (*(volatile uint32_t*)0x40020000)
#define GPIOA_OTYPER   (*(volatile uint32_t*)0x40020004)
#define GPIOA_OSPEEDR  (*(volatile uint32_t*)0x40020008)
#define GPIOA_PUPDR    (*(volatile uint32_t*)0x4002000C)
#define GPIOA_IDR      (*(volatile uint32_t*)0x40020010)
#define GPIOA_ODR      (*(volatile uint32_t*)0x40020014)
#define GPIOA_BSRR     (*(volatile uint32_t*)0x40020018)
#define GPIOA_AFRL     (*(volatile uint32_t*)0x40020020)
#define GPIOA_AFRH     (*(volatile uint32_t*)0x40020024)

/* ================= USART2 ================= */

#define USART2_SR      (*(volatile uint32_t*)0x40004400)
#define USART2_DR      (*(volatile uint32_t*)0x40004404)
#define USART2_BRR     (*(volatile uint32_t*)0x40004408)
#define USART2_CR1     (*(volatile uint32_t*)0x4000440C)
#define USART2_CR2     (*(volatile uint32_t*)0x40004410)
#define USART2_CR3     (*(volatile uint32_t*)0x40004414)

/* ================= SysTick ================= */

#define SYST_CSR       (*(volatile uint32_t*)0xE000E010)
#define SYST_RVR       (*(volatile uint32_t*)0xE000E014)
#define SYST_CVR       (*(volatile uint32_t*)0xE000E018)
#define SYST_CALIB     (*(volatile uint32_t*)0xE000E01C)

void Clock_Enable(void);

void USART2_Init(void);

void USART2_SendChar(char ch);
char USART2_ReadChar(void);

void USART2_SendString(char *str);

void SysTick_Init(void);

void Display_Time(void);
void Display_Lap(void);

void SysTick_Handler(void);

volatile uint32_t ms = 0;
volatile uint32_t sec= 0;
volatile uint32_t min = 0;
volatile uint32_t hour = 0;
volatile uint32_t run = 0;
char buffer[20];


int main(void)
{
    Clock_Enable();

    USART2_Init();

    SysTick_Init();

    USART2_SendString("\r\nSTOPWATCH READY\r\n");
    USART2_SendString("S = Start\r\n");
    USART2_SendString("P = Pause\r\n");
    USART2_SendString("R = Reset\r\n");
    USART2_SendString("L = Lap\r\n");

    while(1)
    {
        /* Check if data received */
        if(USART2_SR & (1 << 5))
        {
            char cmd = (char)USART2_DR;

            if(cmd == 'S' || cmd == 's')
            {
                run = 1;
            }
            else if(cmd == 'P' || cmd == 'p')
            {
                run = 0;
            }
            else if(cmd == 'R' || cmd == 'r')
            {
                run = 0;

                hour = 0;
                min  = 0;
                sec  = 0;
                ms   = 0;
            }
            else if(cmd == 'L' || cmd == 'l')
            {
                Display_Lap();
            }
        }

        Display_Time();
    }
}
void Display_Lap(void)
{
    USART2_SendString("\r\nLAP : ");

    snprintf(buffer,
             sizeof(buffer),
             "%02lu:%02lu:%02lu\r\n",
             (unsigned long)hour,
             (unsigned long)min,
             (unsigned long)sec);

    USART2_SendString(buffer);
}
void Clock_Enable(void)
{
    RCC_AHB1ENR |= (1 << 0);     // GPIOA Clock

    RCC_APB1ENR |= (1 << 17);    // USART2 Clock
}
void USART2_Init(void)
{
    GPIOA_MODER &= ~(0xF << 4);
    GPIOA_MODER |=  (0xA << 4);

    GPIOA_AFRL &= ~(0xFF << 8);
    GPIOA_AFRL |=  (0x77 << 8);

    USART2_BRR = 0x0683;

    USART2_CR1 |= (1 << 3);
    USART2_CR1 |= (1 << 2);

    USART2_CR1 |= (1 << 13);
}
void SysTick_Init(void)
{
    SYST_RVR = 16000 - 1;

    SYST_CVR = 0;

    SYST_CSR = 7;
}
char USART2_ReadChar(void)
{
    while(!(USART2_SR & (1 << 5)));

    return (char)USART2_DR;
}
void SysTick_Handler(void)
{
    ms++;

    if(ms >= 1000)
    {
        ms = 0;

        if(run)
        {
            sec++;

            if(sec >= 60)
            {
                sec = 0;
                min++;
            }

            if(min >= 60)
            {
                min = 0;
                hour++;
            }

            if(hour >= 24)
            {
                hour = 0;
            }
        }
    }
}
void USART2_SendChar(char ch)
{
    while(!(USART2_SR & (1 << 7)));

    USART2_DR = ch;
}
void USART2_SendString(char *str)
{
    while(*str)
    {
        USART2_SendChar(*str++);
    }
}

void Display_Time(void)
{
    static uint32_t old_sec = 999;

     if(old_sec != sec)
    {
        old_sec = sec;

        snprintf(buffer,
                 sizeof(buffer),
                 "\r%02lu:%02lu:%02lu",
                 (unsigned long)hour,
                 (unsigned long)min,
                 (unsigned long)sec);

        USART2_SendString(buffer);
    }
}

/*
void Display_Time(void)
{
    static uint32_t old_sec = 999;

    if(old_sec != sec)
    {
        old_sec = sec;

        snprintf(buffer,sizeof(buffer),
                 "\r%02lu:%02lu:%02lu",
                 (unsigned long)hour,
                 (unsigned long)min,
                 (unsigned long)sec);

        USART2_SendString(buffer);
    }
}
*/
